### ISSUE TITLE
Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

### ISSUE THREAD

**Issue by missnebun** [limberger/terraform-provider-netbox#8]
Looks like this provider needs some love. 
Failed to instantiate provider "netbox" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

**Comment by limberger** [comment]
Yes!
I was retiring, but I changed my mind and went back to work ... Who knows, maybe we can update it?
